### ISSUE TITLE
카카오로 회원가입 할 때 비밀번호 다 똑같은 것 같아요

### ISSUE THREAD

**Issue by sinna94** [BahngJH/KHBooks#4]
@BahngJH 
비밀번호가 코드에 고정되어 [있던데](https://github.com/BahngJH/KHBooks/blob/master/Semi_Project/src/com/kh/member/controller/KaKaoLoginServlet.java)

암호화 되어 있어서 상관은 없는거죠??

**Comment by BahngJH** [comment]
로그인할 때 비밀번호가 공백이면 로그인을 못하게 해놨거든?(공백도 암호화가 가능) 그걸 이용해서 공백을 암호화한 뒤 카카오 계정들은 고정값으로 그걸 넣게 만든거야 즉, 카카오 계정의 회원들은 일반 로그인 로직으로 로그인을 막아놔서 보안상의 이슈를 어느정도 염두해둔거라 걱정하지않아두돼 더 궁금한거 있음 말하구
